<a href="https://colab.research.google.com/github/kiranp7/numpy-task/blob/main/numpy_t.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
primary_array=np.array([1,2,3,4,5])
print(primary_array)

[1 2 3 4 5]


In [ ]:
type(primary_array)

numpy.ndarray

In [ ]:
another_array=np.array([[1,2,3],[4,5,6]])
print(another_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
another_array

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
thrd_array=np.array([[[1,2,3,4],[2,3,4,5]],
 [[5,6,7,8],[4,5,6,7]],[[1,2,9,0],[6,7,8,9]]])
print(thrd_array)
print(thrd_array.shape)

[[[1 2 3 4]
  [2 3 4 5]]

 [[5 6 7 8]
  [4 5 6 7]]

 [[1 2 9 0]
  [6 7 8 9]]]
(3, 2, 4)


In [ ]:
thrd_array.shape

(3, 2, 4)

In [ ]:
thrd_array.ndim

3

In [ ]:
thrd_array.size

24

In [ ]:
thrd_array.dtype

dtype('int64')

In [ ]:
ar=thrd_array.astype('float64')
print(ar.dtype)

float64
